version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@9.0.1

jobs:
  build:
    docker:
      - image: cimg/go
    steps:
      - checkout

      - aws-ecr/auth:
          region: AWS_REGION
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          account-url: AWS_ECR_ACCOUNT_URL

      - run: go run hello.go

      - aws-ecr/build-and-push-image:
          repo: testing-cicd
          tag: latest    

workflows:
  build-and-push-image:
    jobs:
      - build-and-pudh-image:
          context:
            aws_dev
