---
version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@9.0.1

jobs:
  build:
    docker:
      - image: cimg/go:1.21.4
    steps:
      - checkout
      - run: go run hello.go

  deploy:
    docker:
      - image: circleci/aws-cli@4.1.2
    environments:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      AWS_DEFAULT_REGION: ap-south-1  

    steps:
      -  attach_workspace:
          at: .

      - aws-ecr/build-and-push-image:
          account_id: ${AWS_ACCOUNT_ID}
          auth:
            - aws-cli/setup:
                role_arn: arn:aws:iam::240481310194:role/Role-for-circleCi
          context: aws_dev
          repo: testing-cicd
          tag: latest

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
