---
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.0
  aws-ecr: circleci/aws-ecr@9.0.1

jobs:
  build:
    docker:
      - image: cimg/go:1.21.4
    steps:
      - checkout
      - run: go run hello.go

      - aws-ecr/build-and-push-image:
          account_id: ${AWS_ACCOUNT_ID}
          auth:
            - aws-cli/setup:
                role_arn: arn:aws:iam::240481310194:role/Role-for-circleCi
          context: aws_dev
          repo: testing-cicd
          tag: latest

workflows:
  version: 2
  build-and-push-image:
    jobs:
      - build
      - aws-build-and-push-image
