version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.0
  aws-ecr: circleci/aws-ecr@9.0.1

jobs:
  build:
    docker:
      - image: cimg/go:1.21.4
    steps:
      - checkout
      - run: go run hello.go

      - aws-ecr/auth:
          region: AWS_REGION
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          account-url: AWS_ECR_ACCOUNT_URL

workflows:
  version: 2
  build-and-push-image:
    jobs:
      - build
      - aws-ecr/build-and-push-image:
          repo: testing-cicd
          tag: latest
          context:
            aws_dev
          requires:
            - build

