---
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.0
  aws-ecr: circleci/aws-ecr@9.0.1

jobs:
  build:
    docker:
      - image: cimg/go:1.21.4
    steps:
      - checkout
      - run: go run hello.go

      - aws-ecr/build-and-push-image:
          repo: testing-cicd
          tag: latest
          context:
            aws_dev

workflows:
  version: 2
  build:
    jobs:
      - build
