---
version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.2.1

jobs:
  aws-build-and-push:
    docker:
      - image: cimg/go:1.21.4
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          go version
      - run: go run hello.go
      - aws-ecr/build-and-push-image:
          registry-id: AWS_ECR_REGISTRY_ID
          repo: "testing-cicd"
          tag: "${CIRCLE_SHA1}"
          dockerfile: "Dockerfile"
          path: .
          build-path: .


workflows:
  build-and-deploy:
    jobs:
    - aws-build-and-push:
        context:
          - aws_dev






















# version: 2.0
# orbs:
#     aws-ecr: circleci/aws-ecr@9.0
# jobs:
#   test:
#     docker:
#       - image: cimg/go:1.21.4
#     steps:
#       - checkout
#       - setup_remote_docker
#       - run:
#           name: install dependencies
#           command: |
#               apk --no-cache add git
#       - run: go run hello.go
#   aws-ecr/build-and-push-image:
#       repo: testing-cicd
#       tag: $CIRCLE_SHA1
#       context: aws_dev
  # deploy:
  #   docker:
  #     - image: circleci/aws-cli@4.1.2
  #   environment:
  #     AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  #     AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  #     AWS_DEFAULT_REGION: ap-south-1
# workflows:
#   build_and_deploy:
#     jobs:
#       - test
#       - aws-ecr/build-and-push-image:
#           repo: testing-cicd
#           tag: $CIRCLE_SHA1
#           context: aws_dev
#           requires:
#             - test
