version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@9.0.1

jobs:
  aws_ecr:
    docker:
      - image: cimg/go:1.21.4
    steps:
      - checkout
      - run: go run hello.go


      - aws-ecr/build_and_push_image:
          repo: testing-cicd
          tag: latest,myECRRepoTag


workflows:
  build_and_push_to_ecr:
    jobs:
      - aws_ecr:
          context: 
            aws_dev
