---
version: 2.0

jobs:
  test:
    docker:
      - image: cimg/go:1.21.4
    steps:
      - checkout
      - run: go run hello.go
  deploy:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install dependencies
          command: |
              apk --no-cache add git
      - run:
          name: build image and push
          command: ./build.sh

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
